import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import classes from "./layoutStyles.module.scss";
import { MainHeader } from "@/components";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${classes.wrapper}`}>
        <MainHeader />
        <div className={classes.children}>{children}</div>
      </body>
    </html>
  );
}
